[build]
  command = "pnpm install && pnpm build"
  publish = "dist"

# Redirects for SPA support
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/main/index.html"
  status = 200
